model_auto_compact_token_limit = 300000

[tui]
status_line = ["model-with-reasoning", "project-name", "git-branch", "branch-changes", "thread-name", "context-used", "five-hour-limit", "weekly-limit"]
status_line_use_colors = true

[plugins."vercel@claude-plugins-official"]
enabled = false

[plugins."figma@claude-plugins-official"]
enabled = false

[plugins."documents@openai-primary-runtime"]
enabled = false

[plugins."presentations@openai-primary-runtime"]
enabled = false

[plugins."spreadsheets@openai-primary-runtime"]
enabled = false

[plugins."pdf@openai-primary-runtime"]
enabled = false

[plugins."template-creator@openai-primary-runtime"]
enabled = false

[plugins."github@openai-curated-remote"]
enabled = false

[plugins."gmail@openai-curated-remote"]
enabled = false

[plugins."google-calendar@openai-curated-remote"]
enabled = false

[plugins."google-drive@openai-curated-remote"]
enabled = false

[plugins."linear@openai-curated-remote"]
enabled = false
